#
#
# Dockerfile to install golang
# VERSION 2 - EDITION 1

# Base image used is ubuntu

FROM gggaaooppeenngg/ubuntu:golang

#Maintainer: ggaaooppeenngg <gaopeg01 at gmail com>

MAINTAINER ggaaooppeenngg,gaopeg01@gmail.com

#add main.go source file

ADD main.go /home/main.go

#run main.go

CMD ["go","run","home/main.go"]
